---
version: '2'
services:
  metricbeat:
    build:
      context: build/metricbeat
      args:
        ELASTIC_VERSION: "${ELASTIC_VERSION}"
        DOWNLOAD_URL: "${DOWNLOAD_URL}"
    networks:
      - elastic-stack

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    networks:
      - elastic-stack

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    ports:
      - '5601:5601'
    networks:
      - elastic-stack

networks:
  elastic-stack:
